server:
  port: 8080

logging:
  config: classpath:log4j2_springboot.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/papersystem?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.admin.pojo

